name: Build External Help

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths: 'documentation/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building Help File
      env:
        RUNSINACTION: 1
      shell: pwsh
      run: |
        ./build/Build-HelpFile.ps1
